namespace CUM.Installer
{
    internal partial class Installer
    {
        /// <summary>
        /// Mandatory constructor variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Free all resources in use.
        /// </summary>
        /// <param name="disposing">true if the managed resource is to be deleted otherwise false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code automatically generated by the Windows Form Designer

        /// <summary>
        /// Required method for constructor support - do not change
        /// contents of this method using the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Installer));
            this.ProgramsCheckedListBox1 = new System.Windows.Forms.CheckedListBox();
            this.InstallerSplitContainer = new System.Windows.Forms.SplitContainer();
            this.ProgramsCheckedListBox4 = new System.Windows.Forms.CheckedListBox();
            this.ProgramsCheckedListBoxLabel8 = new System.Windows.Forms.Label();
            this.ProgramsCheckedListBox6 = new System.Windows.Forms.CheckedListBox();
            this.ProgramsCheckedListBoxLabel5 = new System.Windows.Forms.Label();
            this.ProgramsCheckedListBoxLabel7 = new System.Windows.Forms.Label();
            this.ProgramsCheckedListBoxLabel4 = new System.Windows.Forms.Label();
            this.ProgramsCheckedListBox8 = new System.Windows.Forms.CheckedListBox();
            this.ProgramsCheckedListBox5 = new System.Windows.Forms.CheckedListBox();
            this.ProgramsCheckedListBox7 = new System.Windows.Forms.CheckedListBox();
            this.ProgramsCheckedListBoxLabel6 = new System.Windows.Forms.Label();
            this.OtherProgramsListBox = new System.Windows.Forms.CheckedListBox();
            this.OtherProgramsLabel = new System.Windows.Forms.Label();
            this.ProgramsCheckedListBox3 = new System.Windows.Forms.CheckedListBox();
            this.ProgramsCheckedListBoxLabel3 = new System.Windows.Forms.Label();
            this.ProgramsCheckedListBox2 = new System.Windows.Forms.CheckedListBox();
            this.ProgramsCheckedListBoxLabel2 = new System.Windows.Forms.Label();
            this.ProgramsCheckedListBoxLabel1 = new System.Windows.Forms.Label();
            this.SelectAllCheckBox = new System.Windows.Forms.CheckBox();
            this.ModeSelectionGroupBox = new System.Windows.Forms.GroupBox();
            this.StartButton = new System.Windows.Forms.Button();
            this.StopButton = new System.Windows.Forms.Button();
            this.DeleteRadioButton = new System.Windows.Forms.RadioButton();
            this.InstallRadioButton = new System.Windows.Forms.RadioButton();
            this.UpdateRadioButton = new System.Windows.Forms.RadioButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.InfoLabel = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.InstallerSplitContainer)).BeginInit();
            this.InstallerSplitContainer.Panel1.SuspendLayout();
            this.InstallerSplitContainer.Panel2.SuspendLayout();
            this.InstallerSplitContainer.SuspendLayout();
            this.ModeSelectionGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // ProgramsCheckedListBox1
            // 
            this.ProgramsCheckedListBox1.BackColor = System.Drawing.Color.PeachPuff;
            this.ProgramsCheckedListBox1.Font = new System.Drawing.Font("Verdana", 8.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBox1.FormattingEnabled = true;
            this.ProgramsCheckedListBox1.IntegralHeight = false;
            this.ProgramsCheckedListBox1.Location = new System.Drawing.Point(8, 32);
            this.ProgramsCheckedListBox1.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ProgramsCheckedListBox1.Name = "ProgramsCheckedListBox1";
            this.ProgramsCheckedListBox1.Size = new System.Drawing.Size(257, 106);
            this.ProgramsCheckedListBox1.TabIndex = 0;
            // 
            // InstallerSplitContainer
            // 
            this.InstallerSplitContainer.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.InstallerSplitContainer.Cursor = System.Windows.Forms.Cursors.VSplit;
            this.InstallerSplitContainer.IsSplitterFixed = true;
            this.InstallerSplitContainer.Location = new System.Drawing.Point(13, 12);
            this.InstallerSplitContainer.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.InstallerSplitContainer.Name = "InstallerSplitContainer";
            // 
            // InstallerSplitContainer.Panel1
            // 
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBox4);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBoxLabel8);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBox6);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBoxLabel5);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBoxLabel7);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBoxLabel4);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBox8);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBox5);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBox7);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBoxLabel6);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.OtherProgramsListBox);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.OtherProgramsLabel);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBox3);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBoxLabel3);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBox2);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBoxLabel2);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBoxLabel1);
            this.InstallerSplitContainer.Panel1.Controls.Add(this.ProgramsCheckedListBox1);
            this.InstallerSplitContainer.Panel1.Cursor = System.Windows.Forms.Cursors.Arrow;
            // 
            // InstallerSplitContainer.Panel2
            // 
            this.InstallerSplitContainer.Panel2.Controls.Add(this.SelectAllCheckBox);
            this.InstallerSplitContainer.Panel2.Controls.Add(this.ModeSelectionGroupBox);
            this.InstallerSplitContainer.Panel2.Controls.Add(this.pictureBox1);
            this.InstallerSplitContainer.Panel2.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.InstallerSplitContainer.Size = new System.Drawing.Size(991, 417);
            this.InstallerSplitContainer.SplitterDistance = 803;
            this.InstallerSplitContainer.SplitterWidth = 5;
            this.InstallerSplitContainer.TabIndex = 1;
            // 
            // ProgramsCheckedListBox4
            // 
            this.ProgramsCheckedListBox4.BackColor = System.Drawing.Color.PeachPuff;
            this.ProgramsCheckedListBox4.Font = new System.Drawing.Font("Verdana", 8.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBox4.FormattingEnabled = true;
            this.ProgramsCheckedListBox4.IntegralHeight = false;
            this.ProgramsCheckedListBox4.Location = new System.Drawing.Point(273, 32);
            this.ProgramsCheckedListBox4.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ProgramsCheckedListBox4.Name = "ProgramsCheckedListBox4";
            this.ProgramsCheckedListBox4.Size = new System.Drawing.Size(257, 106);
            this.ProgramsCheckedListBox4.TabIndex = 18;
            // 
            // ProgramsCheckedListBoxLabel8
            // 
            this.ProgramsCheckedListBoxLabel8.AutoSize = true;
            this.ProgramsCheckedListBoxLabel8.Font = new System.Drawing.Font("Corbel", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBoxLabel8.Location = new System.Drawing.Point(538, 141);
            this.ProgramsCheckedListBoxLabel8.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ProgramsCheckedListBoxLabel8.Name = "ProgramsCheckedListBoxLabel8";
            this.ProgramsCheckedListBoxLabel8.Size = new System.Drawing.Size(88, 22);
            this.ProgramsCheckedListBoxLabel8.TabIndex = 17;
            this.ProgramsCheckedListBoxLabel8.Text = "Graphical:";
            // 
            // ProgramsCheckedListBox6
            // 
            this.ProgramsCheckedListBox6.BackColor = System.Drawing.Color.PeachPuff;
            this.ProgramsCheckedListBox6.Font = new System.Drawing.Font("Verdana", 8.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBox6.FormattingEnabled = true;
            this.ProgramsCheckedListBox6.IntegralHeight = false;
            this.ProgramsCheckedListBox6.Location = new System.Drawing.Point(273, 300);
            this.ProgramsCheckedListBox6.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ProgramsCheckedListBox6.Name = "ProgramsCheckedListBox6";
            this.ProgramsCheckedListBox6.Size = new System.Drawing.Size(257, 106);
            this.ProgramsCheckedListBox6.TabIndex = 9;
            // 
            // ProgramsCheckedListBoxLabel5
            // 
            this.ProgramsCheckedListBoxLabel5.AutoSize = true;
            this.ProgramsCheckedListBoxLabel5.Font = new System.Drawing.Font("Corbel", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBoxLabel5.Location = new System.Drawing.Point(273, 141);
            this.ProgramsCheckedListBoxLabel5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ProgramsCheckedListBoxLabel5.Name = "ProgramsCheckedListBoxLabel5";
            this.ProgramsCheckedListBoxLabel5.Size = new System.Drawing.Size(96, 22);
            this.ProgramsCheckedListBoxLabel5.TabIndex = 16;
            this.ProgramsCheckedListBoxLabel5.Text = "Databases:";
            // 
            // ProgramsCheckedListBoxLabel7
            // 
            this.ProgramsCheckedListBoxLabel7.AutoSize = true;
            this.ProgramsCheckedListBoxLabel7.Font = new System.Drawing.Font("Corbel", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBoxLabel7.Location = new System.Drawing.Point(538, 7);
            this.ProgramsCheckedListBoxLabel7.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ProgramsCheckedListBoxLabel7.Name = "ProgramsCheckedListBoxLabel7";
            this.ProgramsCheckedListBoxLabel7.Size = new System.Drawing.Size(107, 22);
            this.ProgramsCheckedListBoxLabel7.TabIndex = 15;
            this.ProgramsCheckedListBoxLabel7.Text = "Messengers:";
            // 
            // ProgramsCheckedListBoxLabel4
            // 
            this.ProgramsCheckedListBoxLabel4.AutoSize = true;
            this.ProgramsCheckedListBoxLabel4.Font = new System.Drawing.Font("Corbel", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBoxLabel4.Location = new System.Drawing.Point(273, 7);
            this.ProgramsCheckedListBoxLabel4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ProgramsCheckedListBoxLabel4.Name = "ProgramsCheckedListBoxLabel4";
            this.ProgramsCheckedListBoxLabel4.Size = new System.Drawing.Size(121, 22);
            this.ProgramsCheckedListBoxLabel4.TabIndex = 14;
            this.ProgramsCheckedListBoxLabel4.Text = "Programming:";
            // 
            // ProgramsCheckedListBox8
            // 
            this.ProgramsCheckedListBox8.BackColor = System.Drawing.Color.PeachPuff;
            this.ProgramsCheckedListBox8.Font = new System.Drawing.Font("Verdana", 8.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBox8.FormattingEnabled = true;
            this.ProgramsCheckedListBox8.IntegralHeight = false;
            this.ProgramsCheckedListBox8.Location = new System.Drawing.Point(538, 166);
            this.ProgramsCheckedListBox8.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ProgramsCheckedListBox8.Name = "ProgramsCheckedListBox8";
            this.ProgramsCheckedListBox8.Size = new System.Drawing.Size(257, 106);
            this.ProgramsCheckedListBox8.TabIndex = 13;
            // 
            // ProgramsCheckedListBox5
            // 
            this.ProgramsCheckedListBox5.BackColor = System.Drawing.Color.PeachPuff;
            this.ProgramsCheckedListBox5.Font = new System.Drawing.Font("Verdana", 8.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBox5.FormattingEnabled = true;
            this.ProgramsCheckedListBox5.IntegralHeight = false;
            this.ProgramsCheckedListBox5.Location = new System.Drawing.Point(273, 166);
            this.ProgramsCheckedListBox5.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ProgramsCheckedListBox5.Name = "ProgramsCheckedListBox5";
            this.ProgramsCheckedListBox5.Size = new System.Drawing.Size(257, 106);
            this.ProgramsCheckedListBox5.TabIndex = 12;
            // 
            // ProgramsCheckedListBox7
            // 
            this.ProgramsCheckedListBox7.BackColor = System.Drawing.Color.PeachPuff;
            this.ProgramsCheckedListBox7.Font = new System.Drawing.Font("Verdana", 8.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBox7.FormattingEnabled = true;
            this.ProgramsCheckedListBox7.IntegralHeight = false;
            this.ProgramsCheckedListBox7.Location = new System.Drawing.Point(538, 32);
            this.ProgramsCheckedListBox7.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ProgramsCheckedListBox7.Name = "ProgramsCheckedListBox7";
            this.ProgramsCheckedListBox7.Size = new System.Drawing.Size(257, 106);
            this.ProgramsCheckedListBox7.TabIndex = 11;
            // 
            // ProgramsCheckedListBoxLabel6
            // 
            this.ProgramsCheckedListBoxLabel6.AutoSize = true;
            this.ProgramsCheckedListBoxLabel6.Font = new System.Drawing.Font("Corbel", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBoxLabel6.Location = new System.Drawing.Point(273, 275);
            this.ProgramsCheckedListBoxLabel6.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ProgramsCheckedListBoxLabel6.Name = "ProgramsCheckedListBoxLabel6";
            this.ProgramsCheckedListBoxLabel6.Size = new System.Drawing.Size(102, 22);
            this.ProgramsCheckedListBoxLabel6.TabIndex = 8;
            this.ProgramsCheckedListBoxLabel6.Text = "Antiviruses:";
            // 
            // OtherProgramsListBox
            // 
            this.OtherProgramsListBox.BackColor = System.Drawing.Color.PeachPuff;
            this.OtherProgramsListBox.Font = new System.Drawing.Font("Verdana", 8.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.OtherProgramsListBox.FormattingEnabled = true;
            this.OtherProgramsListBox.IntegralHeight = false;
            this.OtherProgramsListBox.Location = new System.Drawing.Point(538, 300);
            this.OtherProgramsListBox.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.OtherProgramsListBox.Name = "OtherProgramsListBox";
            this.OtherProgramsListBox.Size = new System.Drawing.Size(257, 106);
            this.OtherProgramsListBox.TabIndex = 7;
            // 
            // OtherProgramsLabel
            // 
            this.OtherProgramsLabel.AutoSize = true;
            this.OtherProgramsLabel.Font = new System.Drawing.Font("Corbel", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.OtherProgramsLabel.Location = new System.Drawing.Point(538, 275);
            this.OtherProgramsLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.OtherProgramsLabel.Name = "OtherProgramsLabel";
            this.OtherProgramsLabel.Size = new System.Drawing.Size(68, 22);
            this.OtherProgramsLabel.TabIndex = 6;
            this.OtherProgramsLabel.Text = "Others:";
            // 
            // ProgramsCheckedListBox3
            // 
            this.ProgramsCheckedListBox3.BackColor = System.Drawing.Color.PeachPuff;
            this.ProgramsCheckedListBox3.Font = new System.Drawing.Font("Verdana", 8.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBox3.FormattingEnabled = true;
            this.ProgramsCheckedListBox3.IntegralHeight = false;
            this.ProgramsCheckedListBox3.Location = new System.Drawing.Point(8, 300);
            this.ProgramsCheckedListBox3.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ProgramsCheckedListBox3.Name = "ProgramsCheckedListBox3";
            this.ProgramsCheckedListBox3.Size = new System.Drawing.Size(257, 106);
            this.ProgramsCheckedListBox3.TabIndex = 5;
            // 
            // ProgramsCheckedListBoxLabel3
            // 
            this.ProgramsCheckedListBoxLabel3.AutoSize = true;
            this.ProgramsCheckedListBoxLabel3.Font = new System.Drawing.Font("Corbel", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBoxLabel3.Location = new System.Drawing.Point(8, 275);
            this.ProgramsCheckedListBoxLabel3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ProgramsCheckedListBoxLabel3.Name = "ProgramsCheckedListBoxLabel3";
            this.ProgramsCheckedListBoxLabel3.Size = new System.Drawing.Size(52, 22);
            this.ProgramsCheckedListBoxLabel3.TabIndex = 4;
            this.ProgramsCheckedListBoxLabel3.Text = ".NET:";
            // 
            // ProgramsCheckedListBox2
            // 
            this.ProgramsCheckedListBox2.BackColor = System.Drawing.Color.PeachPuff;
            this.ProgramsCheckedListBox2.Font = new System.Drawing.Font("Verdana", 8.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBox2.FormattingEnabled = true;
            this.ProgramsCheckedListBox2.IntegralHeight = false;
            this.ProgramsCheckedListBox2.Location = new System.Drawing.Point(8, 166);
            this.ProgramsCheckedListBox2.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ProgramsCheckedListBox2.Name = "ProgramsCheckedListBox2";
            this.ProgramsCheckedListBox2.Size = new System.Drawing.Size(257, 106);
            this.ProgramsCheckedListBox2.TabIndex = 3;
            // 
            // ProgramsCheckedListBoxLabel2
            // 
            this.ProgramsCheckedListBoxLabel2.AutoSize = true;
            this.ProgramsCheckedListBoxLabel2.Font = new System.Drawing.Font("Corbel", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBoxLabel2.Location = new System.Drawing.Point(8, 141);
            this.ProgramsCheckedListBoxLabel2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ProgramsCheckedListBoxLabel2.Name = "ProgramsCheckedListBoxLabel2";
            this.ProgramsCheckedListBoxLabel2.Size = new System.Drawing.Size(158, 22);
            this.ProgramsCheckedListBoxLabel2.TabIndex = 2;
            this.ProgramsCheckedListBoxLabel2.Text = "Working With Files:";
            // 
            // ProgramsCheckedListBoxLabel1
            // 
            this.ProgramsCheckedListBoxLabel1.AutoSize = true;
            this.ProgramsCheckedListBoxLabel1.Font = new System.Drawing.Font("Corbel", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.ProgramsCheckedListBoxLabel1.Location = new System.Drawing.Point(8, 7);
            this.ProgramsCheckedListBoxLabel1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ProgramsCheckedListBoxLabel1.Name = "ProgramsCheckedListBoxLabel1";
            this.ProgramsCheckedListBoxLabel1.Size = new System.Drawing.Size(86, 22);
            this.ProgramsCheckedListBoxLabel1.TabIndex = 1;
            this.ProgramsCheckedListBoxLabel1.Text = "Browsers:";
            // 
            // SelectAllCheckBox
            // 
            this.SelectAllCheckBox.AutoSize = true;
            this.SelectAllCheckBox.Cursor = System.Windows.Forms.Cursors.Hand;
            this.SelectAllCheckBox.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.SelectAllCheckBox.Font = new System.Drawing.Font("Trebuchet MS", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.SelectAllCheckBox.Location = new System.Drawing.Point(4, 379);
            this.SelectAllCheckBox.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.SelectAllCheckBox.Name = "SelectAllCheckBox";
            this.SelectAllCheckBox.Size = new System.Drawing.Size(101, 27);
            this.SelectAllCheckBox.TabIndex = 0;
            this.SelectAllCheckBox.Text = "Select all";
            this.SelectAllCheckBox.UseVisualStyleBackColor = true;
            this.SelectAllCheckBox.CheckedChanged += new System.EventHandler(this.SelectAllCheckBox_CheckedChanged);
            // 
            // ModeSelectionGroupBox
            // 
            this.ModeSelectionGroupBox.BackColor = System.Drawing.Color.PeachPuff;
            this.ModeSelectionGroupBox.Controls.Add(this.StartButton);
            this.ModeSelectionGroupBox.Controls.Add(this.StopButton);
            this.ModeSelectionGroupBox.Controls.Add(this.DeleteRadioButton);
            this.ModeSelectionGroupBox.Controls.Add(this.InstallRadioButton);
            this.ModeSelectionGroupBox.Controls.Add(this.UpdateRadioButton);
            this.ModeSelectionGroupBox.Font = new System.Drawing.Font("Verdana", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ModeSelectionGroupBox.Location = new System.Drawing.Point(4, 76);
            this.ModeSelectionGroupBox.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ModeSelectionGroupBox.Name = "ModeSelectionGroupBox";
            this.ModeSelectionGroupBox.Padding = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ModeSelectionGroupBox.Size = new System.Drawing.Size(173, 202);
            this.ModeSelectionGroupBox.TabIndex = 0;
            this.ModeSelectionGroupBox.TabStop = false;
            this.ModeSelectionGroupBox.Text = "Mode";
            // 
            // StartButton
            // 
            this.StartButton.BackColor = System.Drawing.Color.Aquamarine;
            this.StartButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.StartButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.StartButton.Font = new System.Drawing.Font("Trebuchet MS", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.StartButton.Location = new System.Drawing.Point(7, 110);
            this.StartButton.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.StartButton.Name = "StartButton";
            this.StartButton.Size = new System.Drawing.Size(158, 40);
            this.StartButton.TabIndex = 3;
            this.StartButton.Text = "Start";
            this.StartButton.UseVisualStyleBackColor = false;
            this.StartButton.Click += new System.EventHandler(this.StartButton_Click);
            // 
            // StopButton
            // 
            this.StopButton.BackColor = System.Drawing.Color.Red;
            this.StopButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.StopButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.StopButton.Font = new System.Drawing.Font("Trebuchet MS", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.StopButton.Location = new System.Drawing.Point(7, 156);
            this.StopButton.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.StopButton.Name = "StopButton";
            this.StopButton.Size = new System.Drawing.Size(158, 40);
            this.StopButton.TabIndex = 3;
            this.StopButton.Text = "Stop";
            this.StopButton.UseVisualStyleBackColor = false;
            this.StopButton.Click += new System.EventHandler(this.StopButton_Click);
            // 
            // DeleteRadioButton
            // 
            this.DeleteRadioButton.AutoSize = true;
            this.DeleteRadioButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.DeleteRadioButton.Font = new System.Drawing.Font("Trebuchet MS", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.DeleteRadioButton.Location = new System.Drawing.Point(7, 77);
            this.DeleteRadioButton.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.DeleteRadioButton.Name = "DeleteRadioButton";
            this.DeleteRadioButton.Size = new System.Drawing.Size(95, 27);
            this.DeleteRadioButton.TabIndex = 2;
            this.DeleteRadioButton.Text = "Uninstall";
            this.DeleteRadioButton.UseVisualStyleBackColor = true;
            // 
            // InstallRadioButton
            // 
            this.InstallRadioButton.AutoSize = true;
            this.InstallRadioButton.Checked = true;
            this.InstallRadioButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.InstallRadioButton.Font = new System.Drawing.Font("Trebuchet MS", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.InstallRadioButton.Location = new System.Drawing.Point(7, 29);
            this.InstallRadioButton.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.InstallRadioButton.Name = "InstallRadioButton";
            this.InstallRadioButton.Size = new System.Drawing.Size(75, 27);
            this.InstallRadioButton.TabIndex = 0;
            this.InstallRadioButton.TabStop = true;
            this.InstallRadioButton.Text = "Install";
            this.InstallRadioButton.UseVisualStyleBackColor = true;
            // 
            // UpdateRadioButton
            // 
            this.UpdateRadioButton.AutoSize = true;
            this.UpdateRadioButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.UpdateRadioButton.Font = new System.Drawing.Font("Trebuchet MS", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.UpdateRadioButton.Location = new System.Drawing.Point(7, 53);
            this.UpdateRadioButton.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.UpdateRadioButton.Name = "UpdateRadioButton";
            this.UpdateRadioButton.Size = new System.Drawing.Size(81, 27);
            this.UpdateRadioButton.TabIndex = 1;
            this.UpdateRadioButton.Text = "Update";
            this.UpdateRadioButton.UseVisualStyleBackColor = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(4, 3);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(175, 73);
            this.pictureBox1.TabIndex = 2;
            this.pictureBox1.TabStop = false;
            // 
            // InfoLabel
            // 
            this.InfoLabel.AutoSize = true;
            this.InfoLabel.Font = new System.Drawing.Font("Trebuchet MS", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.InfoLabel.Location = new System.Drawing.Point(13, 432);
            this.InfoLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.InfoLabel.Name = "InfoLabel";
            this.InfoLabel.Size = new System.Drawing.Size(186, 23);
            this.InfoLabel.TabIndex = 2;
            this.InfoLabel.Text = "No package(s) selected";
            // 
            // Installer
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Sienna;
            this.ClientSize = new System.Drawing.Size(1010, 459);
            this.Controls.Add(this.InfoLabel);
            this.Controls.Add(this.InstallerSplitContainer);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.MaximizeBox = false;
            this.Name = "Installer";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Chocolatey Utils Manager";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.InstallerClosed);
            this.Load += new System.EventHandler(this.Installer_Load);
            this.Shown += new System.EventHandler(this.Installer_Shown);
            this.InstallerSplitContainer.Panel1.ResumeLayout(false);
            this.InstallerSplitContainer.Panel1.PerformLayout();
            this.InstallerSplitContainer.Panel2.ResumeLayout(false);
            this.InstallerSplitContainer.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.InstallerSplitContainer)).EndInit();
            this.InstallerSplitContainer.ResumeLayout(false);
            this.ModeSelectionGroupBox.ResumeLayout(false);
            this.ModeSelectionGroupBox.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal System.Windows.Forms.CheckedListBox ProgramsCheckedListBox1;
        internal System.Windows.Forms.Label ProgramsCheckedListBoxLabel1;
        internal System.Windows.Forms.Label ProgramsCheckedListBoxLabel2;
        internal System.Windows.Forms.CheckedListBox ProgramsCheckedListBox2;
        internal System.Windows.Forms.Label ProgramsCheckedListBoxLabel3;
        internal System.Windows.Forms.CheckedListBox ProgramsCheckedListBox3;
        internal System.Windows.Forms.Label OtherProgramsLabel;
        internal System.Windows.Forms.Label ProgramsCheckedListBoxLabel6;
        internal System.Windows.Forms.CheckedListBox OtherProgramsListBox;
        internal System.Windows.Forms.CheckedListBox ProgramsCheckedListBox6;
        internal System.Windows.Forms.CheckedListBox ProgramsCheckedListBox8;
        internal System.Windows.Forms.CheckedListBox ProgramsCheckedListBox5;
        internal System.Windows.Forms.CheckedListBox ProgramsCheckedListBox7;
        internal System.Windows.Forms.Label ProgramsCheckedListBoxLabel4;
        internal System.Windows.Forms.Label ProgramsCheckedListBoxLabel7;
        internal System.Windows.Forms.Label ProgramsCheckedListBoxLabel5;
        internal System.Windows.Forms.Label ProgramsCheckedListBoxLabel8;
        internal System.Windows.Forms.RadioButton InstallRadioButton;
        internal System.Windows.Forms.RadioButton DeleteRadioButton;
        internal System.Windows.Forms.RadioButton UpdateRadioButton;
        internal System.Windows.Forms.GroupBox ModeSelectionGroupBox;
        internal System.Windows.Forms.Button StartButton;
        internal System.Windows.Forms.CheckBox SelectAllCheckBox;
        internal System.Windows.Forms.PictureBox pictureBox1;
        internal System.Windows.Forms.Label InfoLabel;
        internal System.Windows.Forms.Button StopButton;
        internal System.Windows.Forms.SplitContainer InstallerSplitContainer;
        internal System.Windows.Forms.CheckedListBox ProgramsCheckedListBox4;
    }
}
